doc-warnings: yes
test-warnings: no
strictness: medium
max-line-length: 120
autodetect: yes
requirements:
    - dev-requirements.txt
ignore-paths:
    - apps
    - sandbox
    - pywinauto/unittests
ignore-patterns:
    - ^pywinauto/six.py$